name: tinydip
base: core24
version: '1.0'
summary: Tiny Digital Image Processing Library
description: |
  TinyDIP is a modern C++ library for digital image processing.
  This snap packages the main demonstration executable.

grade: devel # Use 'stable' once you are ready to release to the store
confinement: devmode # Start with 'devmode' to avoid permission issues during testing

parts:
  tinydip:
    plugin: cmake
    source: .
    
    # CMake configuration flags
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      # CUDA is disabled for the base snap build to ensure compatibility.
      # Enabling CUDA in snaps requires the 'nvidia-neon' extension or manual setup.
      - -DENABLE_CUDA=OFF
      # Installing to /usr results in the binary being at $SNAP/usr/bin/TinyDIP
      - -DCMAKE_INSTALL_PREFIX=/usr

    # Build-time dependencies (headers and compilers)
    build-packages:
      - build-essential
      - cmake
      - libopencv-dev
      - libtbb-dev
      - libomp-dev
      - libboost-all-dev
      - pkg-config

    # Runtime dependencies (shared libraries)
    stage-packages:
      - libopencv-core406t64
      - libopencv-imgcodecs406t64
      - libopencv-highgui406t64
      - libopencv-imgproc406t64
      - libtbb12
      - libgomp1
      - libstdc++6
      - libgcc-s1
      # Explicitly stage common graphics backends for OpenCV highgui
      - libgl1
      - libglx-mesa0
      - libegl1
      - libx11-6

apps:
  tinydip:
    # FIX: Updated path to match CMAKE_INSTALL_PREFIX=/usr
    command: usr/bin/TinyDIP
    
    # Plugs allow the app to access system resources
    plugs:
      - home             # Access to user's home directory
      - removable-media  # Access to USBs/External drives
      - opengl           # Required for GUI/Rendering (OpenCV imshow)
      - x11              # Legacy display server support
      - wayland          # Modern display server support